# Generated by Django 4.1.5 on 2023-01-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_object'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object',
        ),
    ]
